djangocc/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^flashcards/', include('flashcards.urls', namespace='flashcards')),
    url(r'^admin/', admin.site.urls),
]

flashcards/urls.py
#FLASHCARDS URL CONF
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'decks/create/', views.createDeck, name='createDeck'),
    url(r'decks/edit/(?P<deck_id>[\d]+)', views.editDeck, name='editDeck'),
    url(r'decks/delete/(?P<deck_id>[\d]+)', views.deleteDeck, name='deleteDeck'),
    url(r'decks/view/(?P<deck_id>[\d]+)', views.viewDeck, name='viewDeck'),
    url(r'cards/create/(?P<deck_id>[\d]+)', views.createCard, name='createCard'),
    url(r'cards/edit/(?P<card_id>[\d]+)', views.editCard, name='editCard'),
    url(r'cards/delete/(?P<card_id>[\d]+)', views.deleteCard, name='deleteCard')
]

flashcards/models.py
from django.db import models
import random

# Create your models here.
class Deck(models.Model):
    title = models.CharField(max_length=64, null=False, blank=False)
    description = models.CharField(max_length=255, null=False, blank=True)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_number_of_cards(self):
        '''
        Returns the number of cards in the decks related
        card_set
        '''
        return self.card_set.count()
    get_number_of_cards.short_description = 'Card Count'

    def get_random_card(self):
        '''
        Returns random card from deckset
        '''
        random_number = random.randint(0, self.card_set.count() - 1)
        random_card = self.card_set.all()[random_number]
        return random_card

class Card(models.Model):
    parentDeck = models.ForeignKey(Deck, on_delete=models.CASCADE)
    front = models.TextField()
    back = models.TextField()

    def __str__(self):
        return self.front

    def has_prev_card(self):
        '''
        Returns true if the card is not the first card
        in the deck.
        '''
        first_card_in_deck = self.parentDeck.card_set.first()
        if self == first_card_in_deck:
            return False
        return True

    def get_prev_card(self):
        '''
        Returns previous card in deck
        '''
        return self.parentDeck.card_set.filter(id__lt=self.id).last()


    def has_next_card(self):
        '''
        Returns true if the card is not the last card
        in the deck
        '''
        last_card_in_deck = self.parentDeck.card_set.last()
        if self == last_card_in_deck:
            return False
        return True

    def get_next_card(self):
        '''
        Returns next card in deck
        '''
        return self.parentDeck.card_set.filter(id__gt=self.id).first()

flashcards/forms.py
from django.forms import ModelForm
from .models import Deck, Card

class DeckForm(ModelForm):
    '''
    Form mapping to the deck model
    '''
    class Meta:
        model = Deck
        fields = ['title', 'description', 'is_active']

class CardForm(ModelForm):
    '''
    Form mapping to the card model
    '''
    class Meta:
        model = Card
        fields = ['parentDeck', 'front', 'back']

djangocc/views.py
from django.shortcuts import render

def home(request):
    '''
    Renders home page
    '''
    context = {}
    return render(request, 'home.html', context)

flashcards/views.py
from django.shortcuts import (
        get_object_or_404,
        HttpResponseRedirect,
        render,
    )
from django.urls import reverse
from .forms import CardForm, DeckForm
from .models import Card, Deck

# Create your views here.
def home(request):
    '''
    Renders the FLASHCARD app home template
    '''
    qs = Deck.objects.order_by('-title').filter(is_active=True)
    context = {'decks': qs}
    return render(request, 'flashcards/home.html', context)

def createCard(request, deck_id):
    '''
    Used to create a card for the deck with the given deck_id
    '''
    deck_obj = get_object_or_404(Deck, id=deck_id)
    if request.method == 'POST':
        form = CardForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('flashcards:viewDeck', args=[deck_obj.id]))
    else:
        form = CardForm(initial={'parentDeck':deck_obj})
    context = {'form': form}
    return render(request, 'flashcards/createAndEditCard.html', context)

def createDeck(request):
    '''
    Renders the form to add new decks to the database
    '''
    if request.method == 'POST':
        # create the form isntance, and populate with data from the request
        form = DeckForm(request.POST)
        # check if the form is valid
        if form.is_valid():
            #save the form, this saves the object to the database
            form.save()
            return HttpResponseRedirect(reverse('flashcards:home'))
    else:
        form = DeckForm()
    context = {'form': form}
    return render(request, 'flashcards/createAndEditDeck.html', context)

def deleteCard(request, card_id):
    '''
    Deletes the card whose id == card_id
    '''
    card_obj = get_object_or_404(Card, id=card_id)
    card_obj.delete()
    return HttpResponseRedirect(reverse('flashcards:home'))

def deleteDeck(request, deck_id):
    '''
    Deletes the deck whose id == deck_id
    '''
    deck_obj = get_object_or_404(Deck, id=deck_id)
    deck_obj.delete()
    return HttpResponseRedirect(reverse('flashcards:home'))

def editCard(request, card_id):
    '''
    Renders the form to edit information about a card
    '''
    card_obj = get_object_or_404(Card, id=card_id)
    if request.method == 'POST':
        form = CardForm(request.POST, instance=card_obj)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('flashcards:home'))
    else:
        form = CardForm(instance=card_obj)
    context = {'form':form, 'edit_mode':True, 'card_obj':card_obj}
    return render(request, 'flashcards/createAndEditCard.html', context)

def editDeck(request, deck_id):
    '''
    Renders the form to edit information about a deck object
    '''
    deck_obj = get_object_or_404(Deck, id=deck_id)
    if request.method == 'POST':
        # create the form isntance, and populate with data from the request
        form = DeckForm(request.POST, instance=deck_obj)
        # check if the form is valid
        if form.is_valid():
            #save the form, this saves the object to the database
            form.save()
            return HttpResponseRedirect(reverse('flashcards:home'))
    else:
        form = DeckForm(instance=deck_obj)
    context = {'form': form, 'edit_mode':True, 'deck_obj':deck_obj}
    return render(request, 'flashcards/createAndEditDeck.html', context)

def viewDeck(request, deck_id):
    '''
    Gets deck from the database.
    Return first card in deck unless card_id is specified in url
    '''
    deck_obj = get_object_or_404(Deck, id=deck_id)
    card_list = deck_obj.card_set.all()
    card_obj = card_list.first()
    if request.method == 'GET' and 'card' in request.GET:
        card_obj = get_object_or_404(Card, id=request.GET['card'])
    context = {'deck_obj': deck_obj, 'card_obj':card_obj}
    return render(request, 'flashcards/viewDeck.html', context)

flashcards/templates/flashcards/createAndEditCard.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
<input type="submit" value="Submit Form">
</form>

{% if edit_mode %}
  <p>Do you want to delete this card?</p>
  <a href="{% url 'flashcards:deleteCard'  card_obj.id %}"> Delete This Card</a>
{% endif %}

{% endblock %}

flashcards/templates/flashcards/createAndEditDeck.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
<input type="submit" value="Submit Form">
</form>

{% if edit_mode %}
  <p>Do you want to delete this deck?</p>
  <a href="{% url 'flashcards:deleteDeck' deck_obj.id %}"> Delete This Deck</a>
{% endif %}

{% endblock %}

flashcards/templates/flashcards/createDeck.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
<input type="submit" value="Submit Form">
</form>
{% endblock %}

flashcards/templates/flashcards/home.html
{% extends 'base.html' %}
{% block content %}
  <div class='homepage-banner'>
    <h1>uStudy</h1>
    <hr>
    <h4>Please select a deck below!</h4>
    <a class='blue-background my-button' href="{% url 'flashcards:createDeck' %}">Create New Deck</a>

      {% if decks %}
          {% for deck in decks %}
            <a class='my-button' href="{% url 'flashcards:viewDeck' deck.id %}">{{deck.title}}</a>
          {% endfor %}
      {% else %}
        <h1>No Decks Found! Contact an Admin!</h1>
      {% endif %}
  </div>
{% endblock %}

flashcards/templates/flashcards/viewDeck.html
{% extends 'base.html' %}

{% block content %}
<div class="deck-header">
  <div class="deck-header-title">
    <h1>{{deck_obj}}</h1>
  </div>
  <div class="deck-header-actions">
    <a href="{% url 'flashcards:editDeck' deck_obj.id %}">edit deck</a><br>
    <a href="{% url 'flashcards:createCard' deck_obj.id %}">add card</a><br>
    {% if card_obj %}
      <a href="{% url 'flashcards:editCard' card_obj.id %}">edit current card</a><br>
    {% endif %}
  </div>
</div>
<hr>

{% if card_obj %}
<div class="notecard-nav text-centered">
  {% if card_obj.has_prev_card %}
    <a href="{% url 'flashcards:viewDeck' deck_obj.id %}?card={{card_obj.get_prev_card.id}}">Prev</a>
  {% endif %}
  {% if deck_obj.get_number_of_cards > 1 %}
  <a href="{% url 'flashcards:viewDeck' deck_obj.id %}?card={{deck_obj.get_random_card.id}}">Random</a>
  {% endif%}
  {% if card_obj.has_next_card %}
    <a href="{% url 'flashcards:viewDeck' deck_obj.id %}?card={{card_obj.get_next_card.id}}">Next</a>
  {% endif %}
</div>

<div class="notecard">
  <div class="notecard-front">
    <p class='text-centered'>Front</p>
    <p>{{card_obj.front}}</p>
  </div>
  <div class="notecard-back">
    <p class='text-centered'>Back</p>
    <p>{{card_obj.back}}</p>
  </div>
</div>

<script type='text/javascript'>
  var front = document.querySelector('.notecard-front');
  var back = document.querySelector('.notecard-back');
  var card = document.querySelector('.notecard');

  card.onclick = function(){
    flipCard();
  }

  function flipCard(){
    if (front.style.display === 'none'){
      front.style.display = 'block';
      back.style.display = 'none';
    } else {
      front.style.display = 'none';
      back.style.display = 'block';
    }

  }

</script>


{% else %}
  <p>No card found. Have you tried to add one?</p>
{% endif %}

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>uStudy</title>
    <link rel='stylesheet' href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <div class='container'>
      <nav>
        <a href="{% url 'home' %}">uStudy</a> |
        <a href="{% url 'flashcards:home' %}">Decks</a> |
        <a href="">About</a> |
        <a href="">Contact</a>
        {% if request.user.is_superuser %}
          | <a href="{% url 'admin:index' %}">Admin Panel</a>
        {% endif %}
      </nav>

      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
        <div class='homepage-banner'>
          <h1>uStudy</h1>
          <hr>
          <h4>Harness the Power of U!</h4>
          <a class='my-button' href="{% url 'flashcards:home' %}">Get Started</a>
        </div>
{% endblock %}